import { Header, ThemeProvider } from '@books-management/libs';
import './global.css';
import { Inter } from 'next/font/google';
import QueryProvider from '@/libs/src/httpservice/queryProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Welcome to Book Management App',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <Header />
          <QueryProvider>{children}</QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
